services:

  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
      target: dev
    volumes:
      - ./auth-service/src:/app
      - ./shared/src:/app/shared
    command: uvicorn src.__main__:app --host 0.0.0.0 --port 8001 --reload

  news-retrieval:
    build:
      context: .
      dockerfile: news-retrieval/Dockerfile
      target: dev
    volumes:
      - ./news-retrieval/src:/app
      - ./shared/src:/app/shared
    command: uvicorn src.__main__:app --host 0.0.0.0 --port 8000 --reload

  signal-detection:
    build:
      context: .
      dockerfile: signal-detection/Dockerfile
      target: dev
    volumes:
      - ./signal-detection/src:/app/src
      - ./shared/src:/app/shared
    command: uvicorn src.__main__:app --host 0.0.0.0 --port 8002 --reload
